#!/bin/bash

# Stop node + swap
systemctl stop node
swapoff /media/nvme/swapfile
sleep 10

# Umount disk, remove existing partition
umount /media/nvme
wipefs -af /dev/nvme0n1

# Format disk
parted /dev/nvme0n1 mklabel gpt -s
parted -a opt /dev/nvme0n1 mkpart primary ext4 0% 100% -s
mkfs.ext4 /dev/nvme0n1p1 -F

#configure node drive
mount /dev/nvme0n1p1 /media/nvme
tune2fs -m .1 /dev/nvme0n1p1
mkdir /media/nvme/Bitcoin
chown -R futurebit /media/nvme/Bitcoin/

#Start node + swap
systemctl start swap
systemctl start node