#!/bin/bash

#TO-DO assume this is not installed in embedded system (ie user git clones or downloads source and installer needs to start from there

apt-get update
apt-get -y upgrade

DEBIAN_FRONTEND=noninteractive apt-get -y install htop iputils-ping zip unzip whois traceroute vim openssh-server curl git libssl-dev libxslt-dev libxml2-dev imagemagick libmagickwand-dev libreadline-dev zlib1g-dev libsqlite3-dev libpq-dev build-essential libxml2-dev build-essential libxslt1-dev zlib1g-dev python-dev

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
APOLLO_DIR=/opt/apolloapi

sudo mkdir -p APOLLO_DIR

sudo chown -R futurebit $APOLLO_DIR  #TO-DO have root run script and permissions

### NVM ###                   TO-DO setup so UI runs on stock NVM install (ie sudo apt install nvm)
echo -e "Installing nvm..."

if [ -e ~/.nvm/nvm.sh ]
then
	echo "nvm installed yet"
else
	echo "Installing nvm"
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
fi

. ~/.nvm/nvm.sh

nvm install 14.16.1
nvm alias default 14.16.1

### SYSTEMD ###
echo -e "Installing systemd..."

sudo cp $DIR/apollo-ui.service /etc/systemd/system/
sudo cp $DIR/apollo-miner.service /etc/systemd/system/
sudo cp $DIR/node.service /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable apollo-ui
sudo systemctl enable apollo-miner
sudo systemctl enable node

#TO-DO Use perminant iptable to redirect ports instead of this script?

grep -q -F "$APOLLO_DIR/scripts/firewall" /etc/rc.local || sudo sed -i "\$i \/opt\/apolloapi\/scripts\/firewall" /etc/rc.local

### SYSTEM ###
echo "Configuring miner system..."

#TO-DO move correct miner binary based on system being installed on

### API ###
echo "Building UI (could take few minutes)..."

# TO-DO we should get git submodules for UI but git should be public for this otherwise you have to pack api+ui together
# git submodule update --init --recursive

npm -g i yarn

cd APOLLO_DIR/apolloui

yarn

yarn build

### START ###
echo "Starting Apollo App..."

sudo bash $APOLLO_DIR/backend/firewall

sudo systemctl start apollo-ui

echo -e "Installation complete"
