#!/bin/bash

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
TMPFILE='/tmp/update_progress'
APOLLO_DIR=/opt/apolloapi

### SYSTEM commands ###
# Write down this line the system commands needed


### Update Miner/Node Binaries ###

echo -e "${YELLOW} ---> Updating System binaries${NC}"

arch=$(uname -m)

cp $APOLLO_DIR/backend/apollo-miner/bin/$arch/apollo-miner $APOLLO_DIR/backend/apollo-miner/futurebit-miner
cp $APOLLO_DIR/backend/node/bin/$arch/bitcoind $APOLLO_DIR/backend/node/bitcoind

# Don't touch below this line
echo "90" > $TMPFILE

### SYSTEMD ###
echo -e "${YELLOW} ---> Updating systemd files${NC}"

cp $APOLLO_DIR/backend/apollo-ui.service /etc/systemd/system/
cp $APOLLO_DIR/backend/apollo-miner.service /etc/systemd/system/
cp $APOLLO_DIR/backend/node.service /etc/systemd/system/

echo -e "${YELLOW} ---> Reloading systemd${NC}"
systemctl daemon-reload

echo "100" > $TMPFILE

echo -e "${YELLOW} ---> Restarting APP${NC}"
systemctl restart apollo-ui
systemctl restart node
systemctl restart apollo-miner
