server=1
daemon=0
natpmp=1
uacomment=FutureBit-Apollo-Node
blocksonly=1
persistmempool=0
dbcache=8192
assumevalid=0000000000000000000067f9f40ca6960173ebee423f6130138762dfc40630bf
includeconf=/var/lib/apollo/bitcoin-auth.conf
includeconf=/var/lib/apollo/bitcoin-api.conf
includeconf=/var/lib/apollo/bitcoin-user.conf
