#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
APOLLO_DIR=/opt/apolloapi

sudo chown -R futurebit $APOLLO_DIR

### NVM ###

if [ -e ~/.nvm/nvm.sh ]
then
	echo "nvm installed yet"
else
	echo "Installing nvm"
	cd ~/
	git clone https://github.com/creationix/nvm.git .nvm
	cd ~/.nvm
	git checkout v0.33.11
fi

. ~/.nvm/nvm.sh

nvm install 9.8.0
nvm alias default 9.8.0

### SYSTEMD ###

sudo cp $DIR/apollo.service /etc/systemd/system/
sudo cp $DIR/bfgminer.service /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable apollo
sudo systemctl enable bfgminer

grep -q -F "$APOLLO_DIR/scripts/firewall" /etc/rc.local || sudo sed -i "\$i \/opt\/apolloapi\/scripts\/firewall" /etc/rc.local

### SYSTEM ###

sudo mkdir -p /var/local/apollo/hwmon
sudo chown futurebit /var/local/apollo/hwmon
if [ -e $APOLLO_DIR/bfgminer.conf ]
then
	sudo touch $APOLLO_DIR/bfgminer.conf
fi
sudo chown futurebit $APOLLO_DIR/bfgminer.conf

### UI ###

cd $APOLLO_DIR
git submodule update --recursive --remote

### API ###

tar xzvf build/futurebit.tar.gz -C $APOLLO_DIR/

### START ###

sudo systemctl start apollo

echo -e "Installation complete"