#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

### NVM ###

if [ -e ~/.nvm/nvm.sh ]
then
	echo "nvm installed yet"
else
	echo "Installing nvm"
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
fi

. ~/.nvm/nvm.sh

nvm install 9.8.0
nvm alias default 9.8.0

### SYSTEMD ###

sudo cp $DIR/apollo.service /etc/systemd/system/
sudo cp $DIR/bfgminer.service /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable apollo
sudo systemctl enable bfgminer

grep -q -F '/opt/apolloapi/scripts/install' /etc/rc.local || sudo sed -i '\$i \/opt\/apolloapi\/scripts\/install' /etc/rc.local

echo -e "Installation complete"