#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

### NVM ###

if [ -e ~/.nvm/nvm.sh ]
then
	echo "nvm installed yet"
else
	echo "Installing nvm"
	cd ~/
	git clone https://github.com/creationix/nvm.git .nvm
	cd ~/.nvm
	git checkout v0.33.11
fi

. ~/.nvm/nvm.sh

nvm install 9.8.0
nvm alias default 9.8.0

### SYSTEMD ###

sudo cp $DIR/apollo.service /etc/systemd/system/
sudo cp $DIR/bfgminer.service /etc/systemd/system/

sudo systemctl daemon-reload

sudo systemctl enable apollo
sudo systemctl enable bfgminer

grep -q -F '/opt/apolloapi/scripts/firewall' /etc/rc.local || sudo sed -i "\$i \/opt\/apolloapi\/scripts\/firewall" /etc/rc.local

### SYSTEM ###

sudo mkdir -p /var/local/apollo/hwmon
sudo chown futurebit /var/local/apollo/hwmon

### UI ###

cd /opt/apolloapi
git submodule update --recursive --remote

### API ###

tar xzvf build/futurebit.tar.gz -C /opt/apolloapi/

### START ###

sudo systemctl start apollo

echo -e "Installation complete"